FROM node:20

RUN apt-get update && apt-get install libvips-dev -y

WORKDIR /opt/


COPY ./package.json ./package-lock.json ./

ENV PATH /opt/node/node_modules/.bin:$PATH


WORKDIR /opt/app/

COPY ./ .

RUN npm install --platform=linux --arch=x64 sharp && npm install --ignore-scripts=false --foreground-scripts --verbose sharp
RUN npm run build

EXPOSE 1337

CMD ["npm", "run", "develop"]